workflows:
  build-and-deploy:
    environment:
      vars:
        # Variáveis de ambiente, se necessário
    jobs:
      - name: Build and Package
        script:
          - cd teste4
          - ./gradlew assembleDebug
          # Outras etapas do fluxo de trabalho
        artifacts:
          - $FCI_BUILD_DIR/$FLUTTER_DIR/build/app/outputs/apk/release/*.apk
