workflows:
  version: 2
  build-and-deploy:
    script:
      - cd teste4
      - ./gradlew assembleDebug
      # Outras etapas do fluxo de trabalho
    artifacts:
      - teste4/build/outputs/apk/debug/*.apk
