workflows:
  build-and-deploy:
    environment:
      vars:
        # Variáveis de ambiente, se necessário
    jobs:
      - name: Build and Package
        script:
          - cd teste4
          - ./gradlew assembleDebug
          # Outras etapas do fluxo de trabalho
        artifacts:
          - teste4/build/outputs/apk/debug/*.apk
